
- name: Sets the host to local
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Execute Rake Task
    shell: |
        rake {{ item }}
    register: out
    loop: "{{ rake_cmd }}"
  
  - debug: var=out.stdout_lines