
- name: Sets the host to local
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Execute Rake Task
    shell: |
        rake {{ item }}
    loop: "{{ rake_cmd }}"
    register: out
    
  - debug: "var=out.results.{{item}}.stdout"
    with_sequence: "0-{{rake_cmd|length - 1}}"